# Generated by Django 4.2.2 on 2023-07-09 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
