# Generated by Django 4.2.2 on 2023-07-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_skill_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.TextField(blank=True, max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_possition',
            field=models.TextField(max_length=60),
        ),
    ]
