# Generated by Django 4.2.2 on 2023-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_alter_experience_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.TextField(max_length=40),
        ),
    ]
