# Generated by Django 4.2.2 on 2023-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_sociallink_alter_profile_age_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=50),
        ),
    ]
