# Generated by Django 4.2.2 on 2023-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.TextField(max_length=20)),
                ('testimonial_job_possition', models.TextField(max_length=50)),
                ('testimonial_feedback', models.TextField()),
                ('testimonial_image', models.ImageField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
