# Generated by Django 4.2.2 on 2023-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='for_me',
            field=models.TextField(default=11, verbose_name=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_feedback',
            field=models.TextField(max_length=400),
        ),
    ]
