# Generated by Django 4.2.2 on 2023-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_profile_for_me_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='for_me',
        ),
        migrations.AddField(
            model_name='profile',
            name='me',
            field=models.TextField(default=111, max_length=300),
            preserve_default=False,
        ),
    ]
