# Generated by Django 4.2.2 on 2023-07-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_personalinfo_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
    ]
