# Generated by Django 4.2.2 on 2023-07-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_mesage_delete_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesage',
            new_name='Message',
        ),
    ]
