# Generated by Django 4.2.2 on 2023-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_rename_mesage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='class_name',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='link_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='link_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
