# Generated by Django 4.2.2 on 2023-07-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_remove_sociallink_link_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
