# Generated by Django 4.2.2 on 2023-07-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_alter_sociallink_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link_name',
            field=models.CharField(max_length=100),
        ),
    ]
